In [1]:
# a list of integers

squares = [1,4,9,16,25,36]

In [2]:
# element at the index position 2

squares[2]

9

In [4]:
# element at the last index position

squares[-1]

36

In [5]:
# slice of list from index position 1 to 2

squares[1:3]

[4, 9]

In [7]:
# slice of list from index position 2 to end

squares[2:]

[9, 16, 25, 36]

In [8]:
# slice of list from index position 2 to next to last element

squares[2:-1]

[9, 16, 25]

In [80]:
squares=

[49, 36, 25, 16, 9, 4, 1]

In [ ]:
squares[:] # the whole list

In [9]:
# append new element to list

squares.append(49)
print(squares)

[1, 4, 9, 16, 25, 36, 49]


In [13]:
# sort list elements in descending order

squares.sort(reverse=True)
squares

[49, 36, 25, 16, 9, 4, 1]

In [15]:
# list of lists
# can be used to represent a 2-dimensional array

x = [[0,1,2,5,3],[5,0,4,3,0],[1,2,5,4,0]]s
x

[[0, 1, 2, 5, 3], [5, 0, 4, 3, 0], [1, 2, 5, 4, 0]]

In [17]:
# 2nd row, 1st column
x[1][0]


5

In [18]:
# 2nd row
x[1]

[5, 0, 4, 3, 0]

In [84]:
# 1st column not resolved
L = [[0,1,2,5,3],[5,0,4,3,0],[1,2,5,4,0]]
for i in range(0,len(L)):
    for j in range(0,len(L[i])):
        L[i][j]+=1
print(L)

[[1, 2, 3, 6, 4], [6, 1, 5, 4, 1], [2, 3, 6, 5, 1]]


In [85]:
# 1st column not resolved
L = [[0,1,2,5,3],[5,0,4,3,0],[1,2,5,4,0]]
for row in L:
    row[1]+=1
print(L)

[[0, 1, 2, 5, 3], [5, 0, 4, 3, 0], [1, 2, 5, 4, 3]]


In [ ]:
# note that there is no easy way to access a "column" in a list of lists

In [19]:
# import numpy (numerical python) package 

import numpy as np

In [45]:
x = np.array([[0,1,2,5,3],[5,0,4,3,0],[1,2,5,4,0]])
x

array([[0, 1, 2, 5, 3],
       [5, 0, 4, 3, 0],
       [1, 2, 5, 4, 0]])

In [22]:
# access element in row 1, column 0

x[1][0]

5

In [27]:
# access first row of array

x[0], x[0,:]

(array([0, 1, 2, 5, 3]), array([0, 1, 2, 5, 3]))

In [46]:
# access first column of array (dont understand)

x[:,1]

array([1, 0, 2])

In [32]:
# convert array to list
x.tolist()

[[0, 1, 2, 5, 3], [5, 0, 4, 3, 0], [1, 2, 5, 4, 0]]

In [57]:
# access rows 0 and 1, columns 3 and 4

x[0],x[1],x[:,3],x[:,4]
x[0:2,3:5] # dont understand

array([[2, 3],
       [4, 4]])

In [60]:
# sorting data in an array

# example: let's say you want to sort array according to last row

x.sort(axis=1) # axis = 0 for down, axis=1 for right
x

array([[0, 1, 2, 3, 5],
       [0, 0, 3, 4, 5],
       [0, 1, 2, 4, 5]])

In [ ]:
# note that the above does not work as intended: each row is independently sorted

In [71]:
x = np.array([[0,1,2,5,3],[5,0,4,3,0],[1,2,5,4,0]])
x

array([[0, 1, 2, 5, 3],
       [5, 0, 4, 3, 0],
       [1, 2, 5, 4, 0]])

In [50]:
# use argsort to determine index (position) of array elements according to sorted order

index = np.argsort(x,axis=1)
index

array([[0, 1, 2, 4, 3],
       [1, 4, 3, 2, 0],
       [4, 0, 1, 3, 2]])

In [53]:
index[2]

array([1, 4, 3, 2, 0])

In [74]:
# sort array according to row 2, in ascending order
xs1 = x[:,index[2]]
xs1

array([[3, 0, 1, 5, 2],
       [0, 5, 0, 3, 4],
       [0, 1, 2, 4, 5]])

In [73]:
# sort array according to row 1, in descending order

xs2 = x[:,index[1][::-1]]
xs2

array([[0, 2, 5, 3, 1],
       [5, 4, 3, 0, 0],
       [1, 5, 4, 0, 2]])

In [ ]:
# also check out numpy.lexsort, which supports sorting in multiple rows or columns